<#
.SYNOPSIS
  Corporate GitLab one-time machine setup (corporate-gitlab plugin).

.DESCRIPTION
  Wires the parts a Claude Code plugin cannot do declaratively, using values you
  provide via environment variables (so nothing corporate is hardcoded in the repo):

    CORP_GIT_HOST       (required)  corporate GitLab host, e.g. gitlab.example.com
    CORP_GIT_NAMESPACE  (required)  your fork namespace, e.g. jdoe
    CORP_GIT_NAME       (required)  commit author name,  e.g. "Jane Doe"
    CORP_GIT_EMAIL      (required)  commit author email, e.g. jane@example.com
    CORP_GIT_JIRA_KEYS  (optional)  pipe-separated Jira project keys -> hard gate, e.g. "ABC|DEF"
    CORP_GIT_JIRA_URL   (optional)  corporate Jira base URL, e.g. https://jira.example.com

  It then:
    1. Conditional git identity: for any repo whose remote is on CORP_GIT_HOST,
       commits are authored as CORP_GIT_NAME <CORP_GIT_EMAIL>, and a commit-msg hook
       adds Signed-off-by, strips AI co-author lines, and (if keys set) requires a
       Jira key. Personal repos are untouched.
    2. Writes corpgit.host / corpgit.namespace to global git config (read by the
       fork-guard push hook).
    3. Claude Code attribution off (no "Co-Authored-By: Claude" / "Generated with").

  The fork->MR push guard is this plugin's own auto-loaded hook - NOT set here.
  The commit-msg hook is COPIED to a stable path (~/.config/git/corp-git-hooks) so it
  survives plugin updates (the plugin install dir changes on update).

  Idempotent; backs up files it edits. Does not push or open anything.
  Requires git >= 2.36 (hasconfig:remote.*.url).
#>
param()
$ErrorActionPreference = 'Stop'

# ---- 0. required inputs ----
$CorpHost = $env:CORP_GIT_HOST
$Ns       = $env:CORP_GIT_NAMESPACE
$Name     = $env:CORP_GIT_NAME
$Email    = $env:CORP_GIT_EMAIL
$JiraKeys = $env:CORP_GIT_JIRA_KEYS   # optional
$JiraUrl  = $env:CORP_GIT_JIRA_URL    # optional

$missing = @()
if (-not $CorpHost) { $missing += 'CORP_GIT_HOST' }
if (-not $Ns)       { $missing += 'CORP_GIT_NAMESPACE' }
if (-not $Name)     { $missing += 'CORP_GIT_NAME' }
if (-not $Email)    { $missing += 'CORP_GIT_EMAIL' }
if ($missing.Count) {
  throw "Set these environment variables before running setup: $($missing -join ', '). See README (corporate-gitlab -> Local setup)."
}

$PluginRoot   = $PSScriptRoot
$SrcCommitMsg = Join-Path $PluginRoot 'git\corp-git-hooks\commit-msg'
if (-not (Test-Path $SrcCommitMsg)) { throw "Missing: $SrcCommitMsg" }
if (-not (Get-Command git -ErrorAction SilentlyContinue)) { throw 'git not found on PATH.' }

$GitCfgDir = Join-Path $env:USERPROFILE '.config\git'
$HooksDir  = Join-Path $GitCfgDir 'corp-git-hooks'
New-Item -ItemType Directory -Force -Path $HooksDir | Out-Null

# Copy the commit-msg hook to the stable location, LF-only (so the shebang works under Git Bash).
$body = (Get-Content $SrcCommitMsg -Raw) -replace "`r`n","`n"
[System.IO.File]::WriteAllText((Join-Path $HooksDir 'commit-msg'), $body)
$HooksDirFwd = ($HooksDir -replace '\\','/')
Write-Host "Copied commit-msg hook -> $HooksDir"

# ---- 1a. installed corporate gitconfig (identity + hooksPath + Jira gate) ----
$CorpCfg = Join-Path $GitCfgDir 'corp-git.gitconfig'
$cfg = @"
# Generated by claude-loadout corporate-gitlab plugin (setup.ps1)
[user]
	name = $Name
	email = $Email
[core]
	hooksPath = $HooksDirFwd
"@
if ($JiraKeys -or $JiraUrl) {
  $cfg += "`n[corpgit]"
  if ($JiraKeys) { $cfg += "`n`tjiraKeys = $JiraKeys" }
  if ($JiraUrl)  { $cfg += "`n`tjiraUrl = $JiraUrl" }
}
$cfg | Set-Content -Path $CorpCfg -Encoding UTF8
Write-Host "Wrote $CorpCfg (identity + hooksPath -> $HooksDirFwd)"

# ---- 1b. host/namespace in global config (read by the fork-guard push hook) ----
git config --global corpgit.host $CorpHost
git config --global corpgit.namespace $Ns
Write-Host "Set global corpgit.host=$CorpHost  corpgit.namespace=$Ns"

# ---- 1c. conditional includes in ~/.gitconfig ----
$GitConfig = Join-Path $env:USERPROFILE '.gitconfig'
$existing  = if (Test-Path $GitConfig) { Get-Content $GitConfig -Raw } else { '' }
if ($existing -match 'corp-git\.gitconfig') {
  Write-Host "~/.gitconfig already references corp-git.gitconfig - skipping include."
} else {
  if (Test-Path $GitConfig) { Copy-Item $GitConfig "$GitConfig.bak-$(Get-Date -Format yyyyMMdd-HHmmss)" }
  $block = @"

# claude-loadout: corporate identity for $CorpHost
[includeIf "hasconfig:remote.*.url:ssh://git@$CorpHost/**"]
	path = ~/.config/git/corp-git.gitconfig
[includeIf "hasconfig:remote.*.url:git@${CorpHost}:**"]
	path = ~/.config/git/corp-git.gitconfig
[includeIf "hasconfig:remote.*.url:https://$CorpHost/**"]
	path = ~/.config/git/corp-git.gitconfig
"@
  Add-Content -Path $GitConfig -Value $block -Encoding UTF8
  Write-Host "Added conditional includes to $GitConfig"
}

# ---- 2. Claude settings: attribution off (no AI co-author) ----
$SettingsDir  = Join-Path $env:USERPROFILE '.claude'
$SettingsPath = Join-Path $SettingsDir 'settings.json'
New-Item -ItemType Directory -Force -Path $SettingsDir | Out-Null

function ConvertTo-HashtableDeep($obj) {
  if ($null -eq $obj) { return $null }
  if ($obj -is [System.Management.Automation.PSCustomObject]) {
    $h = [ordered]@{}; foreach ($p in $obj.PSObject.Properties) { $h[$p.Name] = ConvertTo-HashtableDeep $p.Value }; return $h
  }
  if ($obj -is [System.Collections.IEnumerable] -and $obj -isnot [string]) {
    return @($obj | ForEach-Object { ConvertTo-HashtableDeep $_ })
  }
  return $obj
}

if (Test-Path $SettingsPath) {
  Copy-Item $SettingsPath "$SettingsPath.bak-$(Get-Date -Format yyyyMMdd-HHmmss)"
  $raw = Get-Content $SettingsPath -Raw
  $settings = if ([string]::IsNullOrWhiteSpace($raw)) { [ordered]@{} } else { ConvertTo-HashtableDeep ($raw | ConvertFrom-Json) }
} else { $settings = [ordered]@{} }

if ($settings.Contains('includeCoAuthoredBy')) {
  Write-Warning "settings.json has 'includeCoAuthoredBy'; leaving it. (Don't set it together with 'attribution'.) Ensure it is false for clean commits."
} elseif ($settings.Contains('attribution')) {
  Write-Host "'attribution' already present in settings.json - leaving as-is."
} else {
  $settings['attribution'] = [ordered]@{ commit = ''; pr = '' }
  ($settings | ConvertTo-Json -Depth 30) | Set-Content -Path $SettingsPath -Encoding UTF8
  Write-Host "Set attribution.commit/pr = '' (no AI co-author / 'Generated with' line)."
}

Write-Host ""
Write-Host "Done. Restart Claude Code so the attribution change is picked up."
Write-Host "Verify identity in a corporate repo:  git -C <corp-repo> config user.email"
Write-Host "Fork namespace: '$Ns' (change via env CORP_GIT_NAMESPACE + re-run, or git config --global corpgit.namespace)."
