#!/usr/bin/env bash
#
# Corporate GitLab one-time machine setup (corporate-gitlab plugin).
# Windows users: run setup.ps1 instead.
#
# Provide your corporate values via environment variables (nothing is hardcoded):
#   CORP_GIT_HOST       (required)  corporate GitLab host, e.g. gitlab.example.com
#   CORP_GIT_NAMESPACE  (required)  your fork namespace, e.g. jdoe
#   CORP_GIT_NAME       (required)  commit author name,  e.g. "Jane Doe"
#   CORP_GIT_EMAIL      (required)  commit author email, e.g. jane@example.com
#   CORP_GIT_JIRA_KEYS  (optional)  pipe-separated Jira project keys -> hard gate, e.g. "ABC|DEF"
#   CORP_GIT_JIRA_URL   (optional)  corporate Jira base URL, e.g. https://jira.example.com
#
# Wires the parts a Claude Code plugin cannot do declaratively:
#   1. Conditional git identity for CORP_GIT_HOST repos + a commit-msg hook
#      (Signed-off-by, strip AI co-author, require a Jira key if keys set).
#   2. corpgit.host / corpgit.namespace in global git config (read by fork-guard).
#   3. Claude Code attribution off (no Co-Authored-By / "Generated with Claude Code").
#
# The fork->MR push guard is this plugin's own auto-loaded hook - NOT set here.
# The commit-msg hook is COPIED to a stable path (~/.config/git/corp-git-hooks) so it
# survives plugin updates. Idempotent; backs up files it edits. Requires git >= 2.36, jq.

set -euo pipefail

# ---- 0. required inputs ----
missing=()
[ -n "${CORP_GIT_HOST:-}" ]      || missing+=("CORP_GIT_HOST")
[ -n "${CORP_GIT_NAMESPACE:-}" ] || missing+=("CORP_GIT_NAMESPACE")
[ -n "${CORP_GIT_NAME:-}" ]      || missing+=("CORP_GIT_NAME")
[ -n "${CORP_GIT_EMAIL:-}" ]     || missing+=("CORP_GIT_EMAIL")
if [ "${#missing[@]}" -gt 0 ]; then
  echo "Set these environment variables before running setup: ${missing[*]}" >&2
  echo "See README (corporate-gitlab -> Local setup)." >&2
  exit 1
fi
CORP_HOST="$CORP_GIT_HOST"
NS="$CORP_GIT_NAMESPACE"
NAME="$CORP_GIT_NAME"
EMAIL="$CORP_GIT_EMAIL"
JIRA_KEYS="${CORP_GIT_JIRA_KEYS:-}"
JIRA_URL="${CORP_GIT_JIRA_URL:-}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_COMMIT_MSG="$SCRIPT_DIR/git/corp-git-hooks/commit-msg"
[ -f "$SRC_COMMIT_MSG" ] || { echo "Missing: $SRC_COMMIT_MSG" >&2; exit 1; }
command -v git >/dev/null 2>&1 || { echo "git not found on PATH." >&2; exit 1; }
command -v jq  >/dev/null 2>&1 || { echo "jq required (brew install jq | apt-get install -y jq)." >&2; exit 1; }

GITCFG_DIR="$HOME/.config/git"
HOOKS_DIR="$GITCFG_DIR/corp-git-hooks"
mkdir -p "$HOOKS_DIR"

# Copy the commit-msg hook to the stable location (survives plugin updates).
cp "$SRC_COMMIT_MSG" "$HOOKS_DIR/commit-msg"
chmod +x "$HOOKS_DIR/commit-msg" 2>/dev/null || true
echo "Copied commit-msg hook -> $HOOKS_DIR"

# ---- 1a. installed corporate gitconfig (identity + hooksPath + Jira gate) ----
CORP_CFG="$GITCFG_DIR/corp-git.gitconfig"
{
  echo "# Generated by claude-loadout corporate-gitlab plugin (setup.sh)"
  echo "[user]"
  echo "	name = $NAME"
  echo "	email = $EMAIL"
  echo "[core]"
  echo "	hooksPath = $HOOKS_DIR"
  if [ -n "$JIRA_KEYS" ] || [ -n "$JIRA_URL" ]; then
    echo "[corpgit]"
    [ -n "$JIRA_KEYS" ] && echo "	jiraKeys = $JIRA_KEYS"
    [ -n "$JIRA_URL" ]  && echo "	jiraUrl = $JIRA_URL"
  fi
} > "$CORP_CFG"
echo "Wrote $CORP_CFG (identity + hooksPath -> $HOOKS_DIR)"

# ---- 1b. host/namespace in global config (read by the fork-guard push hook) ----
git config --global corpgit.host "$CORP_HOST"
git config --global corpgit.namespace "$NS"
echo "Set global corpgit.host=$CORP_HOST  corpgit.namespace=$NS"

# ---- 1c. conditional includes in ~/.gitconfig ----
GITCONFIG="$HOME/.gitconfig"
if [ -f "$GITCONFIG" ] && grep -q 'corp-git.gitconfig' "$GITCONFIG"; then
  echo "~/.gitconfig already references corp-git.gitconfig - skipping include."
else
  [ -f "$GITCONFIG" ] && cp "$GITCONFIG" "$GITCONFIG.bak-$(date +%Y%m%d-%H%M%S)"
  cat >> "$GITCONFIG" <<EOF

# claude-loadout: corporate identity for $CORP_HOST
[includeIf "hasconfig:remote.*.url:ssh://git@$CORP_HOST/**"]
	path = ~/.config/git/corp-git.gitconfig
[includeIf "hasconfig:remote.*.url:git@$CORP_HOST:**"]
	path = ~/.config/git/corp-git.gitconfig
[includeIf "hasconfig:remote.*.url:https://$CORP_HOST/**"]
	path = ~/.config/git/corp-git.gitconfig
EOF
  echo "Added conditional includes to $GITCONFIG"
fi

# ---- 2. Claude settings: attribution off (no AI co-author) ----
SETTINGS_DIR="$HOME/.claude"
SETTINGS="$SETTINGS_DIR/settings.json"
mkdir -p "$SETTINGS_DIR"

if [ -f "$SETTINGS" ]; then
  cp "$SETTINGS" "$SETTINGS.bak-$(date +%Y%m%d-%H%M%S)"
  CUR="$(cat "$SETTINGS")"
  [ -n "${CUR//[[:space:]]/}" ] || CUR='{}'
else
  CUR='{}'
fi

if printf '%s' "$CUR" | jq -e 'has("includeCoAuthoredBy")' >/dev/null 2>&1; then
  echo "WARNING: settings.json has 'includeCoAuthoredBy'; leaving it (ensure it is false). Not adding 'attribution' to avoid a conflict." >&2
elif printf '%s' "$CUR" | jq -e 'has("attribution")' >/dev/null 2>&1; then
  echo "'attribution' already present - leaving as-is."
else
  printf '%s' "$CUR" | jq '.attribution = {commit:"", pr:""}' > "$SETTINGS.tmp" && mv "$SETTINGS.tmp" "$SETTINGS"
  echo "Set attribution.commit/pr = '' (no AI co-author / 'Generated with' line)."
fi

echo
echo "Done. Restart Claude Code so the attribution change is picked up."
echo "Verify identity in a corporate repo:  git -C <corp-repo> config user.email"
echo "Fork namespace: '$NS' (change via env CORP_GIT_NAMESPACE + re-run, or git config --global corpgit.namespace)."
